#ifndef __UNIUBI_DDS_MOTION_ODOMETRY_IDL_H_
#define __UNIUBI_DDS_MOTION_ODOMETRY_IDL_H_

module uniubi {
    module msg {
        module dds_ {
            typedef float OdomVector3[3];

            struct MotionOdometry_ {
                OdomVector3 position;
                OdomVector3 velocity;
                float   yaw;
                float   yawSpeed;
                uint64  timestampUs;
                uint32  epoch;
                boolean valid;
            };
        };
    };
};

#endif // __UNIUBI_DDS_MOTION_ODOMETRY_IDL_H_
